import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./styles/style.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sara Rigatti Portfolio Site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <html lang="en">
        <body>
            <nav>
            <div className="nav-left">
                <a href="/" className="logo">
                    <img src="images/logo.png" />
                </a>
            </div>

            <div className="nav-links">
                <Link href="/">Home</Link>
                <Link href="/experience">Experience</Link>
                <Link href="/projects">Projects</Link>
            </div>

            <div className="nav-right">
                <a href="/contact/" className="button">Contact</a>
            </div>
            </nav>
        {children}
      </body>
    </html>
  );
}
